### ISSUE TITLE
Delaying trading until Market open 15 minutes?

### ISSUE THREAD

**Issue by jamesliu1** [Matt-Weiss/alpaca-trading#2]
Thank you for updating the code to use Alpaca's new API (v2).
Just curious, in momentum_algo.py line 401,
is there any specific reason to use "while since_market_open // 60 <= **4**" here,
instead of "since_market_open // 60 <= **14**" (as in the original algo)?
i.e. Should we wait 15 minutes, or 5 minutes after market open? Thanks.

**Comment by Matt-Weiss** [comment]
Sorry for the delay on this, I haven't opened the email associated with my github for quite some time. Any changes I made to the algo were just for my own experimentation purposes. I've honestly abandoned the project due to small portfolio size and the ongoing issues with brokers using payment for order flow. 

As far as I understand it, the 15 minute delay was not anything required by Alpaca, but rather was an attempt by the algorithm to avoid the volatility that comes at market open. At one point I was attempting to see if there was a way to leverage that volatility rather than avoid it. Unfortunately my knowledge of market dynamics isn't great, and I was unable to make any substantial improvements to the Profit/Loss provided by the base algo.
